services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - ../../todo/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - task-net
  app:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
    container_name: goapp
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    networks:
      - task-net
  tg-bot:
    build:
      context: ..
      dockerfile: ./buildtg/Dockerfile
    container_name: tgbot
    depends_on:
      - postgres
    networks:
      - task-net

volumes:
  db-data:

networks:
  task-net: