services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: taskdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - task-net

  backend:
    build: .
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: taskdb
      DB_HOST: localhost
      DB_PORT: 5431
    ports:
      - "8080:8080"
    links:
      - postgres

volumes:
  db-data:

networks:
  task-net:
